cmake_minimum_required(VERSION 3.8)
project(common_msgs)

if(CMAKE_COMPILER_IS_GNUCXX OR CMAKE_CXX_COMPILER_ID MATCHES "Clang")
  add_compile_options(-Wall -Wextra -Wpedantic)
endif()

find_package(ament_cmake REQUIRED)
find_package(rosidl_default_generators REQUIRED)

find_package(std_msgs REQUIRED)
find_package(geometry_msgs REQUIRED)
find_package(builtin_interfaces REQUIRED)


rosidl_generate_interfaces(${PROJECT_NAME}
  "msg/Action.msg"
  "msg/AreaUpdateRequest.msg"
  "msg/AreaUpdateResponse.msg"
  "msg/Buttons.msg"
  "msg/CameraObstacle.msg"
  "msg/CameraObstacles.msg"
  "msg/CloseObjects.msg"
  "msg/Command.msg"
  "msg/DelayStat.msg"
  "msg/DurationStamped.msg"
  "msg/GridFeature.msg"
  "msg/EmergencySim.msg"
  "msg/Event.msg"
  "msg/Events.msg"
  "msg/ExpandedEvent.msg"
  "msg/ExpandedEvents.msg"
  "msg/ExpandedPlannedRoute.msg"
  "msg/FailureCommandArray.msg"
  "msg/FailureCommand.msg"
  "msg/Float32MultiArrayExtended.msg"
  "msg/GNSS.msg"
  "msg/Header.msg"
  "msg/Image.msg"
  "msg/InternalReport.msg"
  "msg/J1939DM1.msg"
  "msg/J1939DTC.msg"
  "msg/J1939Lamp.msg"
  "msg/LidarOdometry.msg"
  "msg/LoadFinished.msg"
  "msg/LowLevelEvents.msg"
  "msg/LowLevelStatus.msg"
  "msg/Maneuver.msg"
  "msg/ManeuverPoint.msg"
  "msg/ManeuverUpdateNotification.msg"
  "msg/MarkerArray.msg"
  "msg/Marker.msg"
  "msg/MovePermission.msg"
  "msg/MovingError.msg"
  "msg/MovingRegime.msg"
  "msg/NmeaGGA.msg"
  "msg/NodesControl.msg"
  "msg/ObjectDistance.msg"
  "msg/ObjectStatus.msg"
  "msg/ObstacleArray.msg"
  "msg/Obstacle.msg"
  "msg/ObstaclesTrajectories.msg"
  "msg/ObstacleTrajectory.msg"
  "msg/OperatorRequest.msg"
  "msg/Orientation.msg"
  "msg/OrientationStamped.msg"
  "msg/PitZone.msg"
  "msg/Plan.msg"
  "msg/PlannedRouteArray.msg"
  "msg/PlannedRoute.msg"
  "msg/Position.msg"
  "msg/PositionStamped.msg"
  "msg/Progress.msg"
  "msg/PureState.msg"
  "msg/Quality.msg"
  "msg/QualityStamped.msg"
  "msg/RegimeChangeReason.msg"
  "msg/RegimeInterval.msg"
  "msg/RemoteControlRequest.msg"
  "msg/RemoteControlResponse.msg"
  "msg/RemoteState.msg"
  "msg/RouteDiff.msg"
  "msg/RoutePoint.msg"
  "msg/RouteType.msg"
  "msg/ScodObject.msg"
  "msg/ScodObjects.msg"
  "msg/SensorQualityData.msg"
  "msg/SensorQuality.msg"
  "msg/ShovelBucket.msg"
  "msg/ServiceDesk.msg"
  "msg/ShovelGeometries.msg"
  "msg/ShovelGeometryMapping.msg"
  "msg/ShovelGeometryMappings.msg"
  "msg/ShovelGeometry.msg"
  "msg/ShovelStatus.msg"
  "msg/ShovelTempGeometries.msg"
  "msg/ShovelTempGeometry.msg"
  "msg/ShovelTempTruckPlanRoute.msg"
  "msg/ShovelTruckStatus.msg"
  "msg/SpatialGraphArray.msg"
  "msg/SpatialGraph.msg"
  "msg/SpeedLimit.msg"
  "msg/Speed.msg"
  "msg/SpeedStamped.msg"
  "msg/StartupEvent.msg"
  "msg/State.msg"
  "msg/StringStamped.msg"
  "msg/SystemStatus.msg"
  "msg/Trajectory.msg"
  "msg/TrajectoryPoint.msg"
  "msg/UnloaderState.msg"
  "msg/Uint8MultiArrayExtended.msg"
  "msg/TransmissionContactorsFeedback.msg"
  "msg/TruckEvent.msg"
  "msg/TruckEvents.msg"
  "msg/TruckState.msg"
  "msg/VehiclePosition.msg"
  "msg/VehicleStatus.msg"
  "msg/VehLinkedImu.msg"
  "msg/Vertices.msg"
  "msg/WheelPlan.msg"
  "msg/WheelSpeed.msg"
  DEPENDENCIES
    std_msgs
    geometry_msgs
    builtin_interfaces
)

ament_export_dependencies(rosidl_default_runtime)
ament_package()