int8 lsmi  # SAE lamp status malfunction indicator
int8 lsrs  # SAE lamp status red stop
int8 lsaw  # SAE lamp status amber warning
int8 lspl  # SAE lamp status protect
int8 flmi  # SAE flash lamp malfunction indicator
int8 flrs  # SAE flash lamp red stop
int8 flaw  # SAE flash lamp amber warning
int8 flpl  # SAE flash lamp protect

# SAE lamp status constants
# int8 OFF=0
# int8 ON=1
# int8 Short_MIL=2
# int8 NA=3

# SAE flash lamp constants
# int8 Slow_Flash=0
# int8 Fast_Flash=1
# int8 Class_C_DTC=2
# int8 NA=3