std_msgs/Header header
common_msgs/Header info
string request_id
uint32 seq_number
uint32 object_id
uint16 request_reason
uint16 MANEUVER_CALC_ERROR = 400
uint16 BLOCKED_BY_PERMISSION = 401
uint16 BLOCKED_BY_OBSTACLE = 402
uint16 BLOCKED_BY_ROUTE_SHIFT = 403
uint16 NEED_UNDLOAD = 405
uint16 NEED_LOAD = 406
uint16 FINISH_REQUEST = 200
uint16 REMOTE_CONTROL_REQUEST = 201
uint16 REQUEST_AUTONOMOUS_MODE = 202
uint16 BUG_INFO_REQUEST = 418
